name: Linting

on: [push, pull_request]

env:
  PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
  PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PUBLIC_SUPABASE_ANON_KEY }}
  PRIVATE_SUPABASE_SERVICE_ROLE: ${{ secrets.PRIVATE_SUPABASE_SERVICE_ROLE }}
  PRIVATE_STRIPE_API_KEY: ${{ secrets.PRIVATE_STRIPE_API_KEY }}

jobs:
  build_and_test:
    name: Linting and Typechecking
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: NPM install
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Typechecking
        run: npm run check
